### ISSUE TITLE
Camera PointCloud in Collision Example

### ISSUE THREAD

**Issue by WaltzBinaire** [cabbibo/PhysicsRenderer#1]
Hey i have a question - i player around with your collision example. And i think there is a general thing i dont get. When i scroll the mousewheel to move in - then on a certain point the particles ALL dissappear. Why is it so...i just dont get it.
This might be not an issue of your library - but it would be very nice if you could point me in the right direction.
thank you

**Comment by inconvergent** [comment]
check line 65 in the example. you are probably moving the object/camera so that the object is no longer inside the near and far distance.

from http://threejs.org/docs/#Reference/Cameras/PerspectiveCamera:

PerspectiveCamera( fov, aspect, near, far )

fov — Camera frustum vertical field of view.
aspect — Camera frustum aspect ratio.
near — Camera frustum near plane.
far — Camera frustum far plane.

**Comment by WaltzBinaire** [comment]
hmm but the problem is - that if clipping occurs - the individual particles will be cut off. But in this example all turn off in the same moment. 

example:
http://cabbi.bo/PhysicsRenderer/examples/collisions.html

if you scroll in till the particles are gone...and then look down - that particles come back - sorry for my noobness - but i just dont get this

**Comment by inconvergent** [comment]
Allright, I don't know this code well enough. I'm guessing @cabbibo will have an answer for you!

**Comment by inconvergent** [comment]
It might just be that the clipping occurs on the centroid of the point cloud though, but I'm guessing.

**Comment by cabbibo** [comment]
@princemio @inconvergent Good catch!  the problem there is that you need to turn off frustumCulled for the particles. Because the positions of the lookup for the particles, they're actual 'threejs' positions will range from 0 --> 1 , and if these points exist within an area that the view frustum clips, they will disappear! fixing it right now!

**Comment by WaltzBinaire** [comment]
Whoa thanks man for the insight and explanation!!

**Comment by cabbibo** [comment]
@princemio no problem! this same problem occurs whenever you are doing vertex shaders that dramatically change the position of the original verts as well, so if in my vertex shader, I shift all the points 100 to the right, and thats where the camera is looking ( but it can't see where their original positions were ) than the object won't show up at all!

**Comment by WaltzBinaire** [comment]
oh ok ...and can this be fixed...i mean its quite interesting - especially for physics...if i spawn particles from a emittertexture...and want to follow them with the camera (using your physicsrenderer) how they travel through space...they wont show up as soon as the camera doesnt catch the emitted particles?

**Comment by cabbibo** [comment]
@princemio the new gh-pages and masters have had fixes pushed to them, so the particles should always show up even if you aren't looking at the origin.

**Comment by WaltzBinaire** [comment]
here is an example from emission from an object...i have this character...render his vertex info to a 2d rendertarget ...and then i animate them 

https://www.facebook.com/video.php?v=838924942831287&set=vb.195052427218545&type=2&theater
